services:
    alfredoramos.hide.listener:
        class: alfredoramos\hide\event\listener
        arguments:
            - '@alfredoramos.hide.helper'
        tags:
            - { name: event.listener }

    alfredoramos.hide.helper:
        class: alfredoramos\hide\includes\helper
        arguments:
            - '@dbal.conn'
            - '@filesystem'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
